server
{
	listen localhost:8080;
	server_name cgi_test;

	cgi_handler php /usr/bin/php-cgi;
	cgi_handler .py /usr/bin/python3;
	cgi_handler .cgi /usr/bin/env;

	location /
	{
		cgi_handler php /usr/bin/php-cgi;
		cgi_handler .py /usr/bin/python3;
		cgi_handler .cgi /usr/bin/env;
		index index.html;
	}

	location /admin
	{
		cgi_handler php /bin/echo;
		index index.html;
	}
}

server

{
	listen localhost:8081;
	server_name cgi_test2;

	cgi_handler .py /usr/bin/python3;
}