root /www;

error_page 403 error/403.html;
error_page 404 error/404.html;

client_max_body_size 420;

index index.html;

server {
      server_name server1;

      listen localhost:8080;
      listen localhost:8081;
      listen 127.0.0.42:8082;
      
      # Is not allowed due to duplicated address:port 
      # listen 127.0.0.1:8080;

      # Is not allowed due to duplicated port
      # listen 127.42.42.42:8080;

      client_max_body_size 100000000;

      # Test limit_except
      location / {
            limit_except GET;
      }

      # Test autoindex
      location /autoindex {
            autoindex on;
      }

      # Test redirection
      location /redirection {
            return /;
      }

      location /get {
            limit_except GET;
      }

      location /not_allowed_delete
      {
      }

      # Test DELETE request
      location /allowed_delete
      {
            limit_except GET DELETE;
      }

      # Test CGIs
      location /cgi-bin
      {
            limit_except GET POST;
            cgi_handler .py /usr/bin/python3;
            cgi_handler .pl /usr/bin/perl;
      }

      cgi_handler test1 test2;
      cgi_handler test1 test1;
	cgi_handler .py /usr/bin/python3;
}

server {
      listen 127.0.0.1:1234;
      # listen 127.42.42.42:8080;

      server_name server2;
}

autoindex off;
