root toto;
error_page ahaha hehehe;
client_max_body_size 42;
index toto tata titi;

server {
      # listen ncdkjsk:8080;
      # listen 12.12.12.12:8080;
      listen localhost:8080;

      server_name server1;
      
      client_max_body_size 1000;
      
      # location / {
      #       cgi_handler test3 test4;
      #       index html2;
      # }

      # location /toto {
            
      # }

      cgi_handler test1 test2;
      cgi_handler test1 test1;
      # toto;
}

server {
      listen 2222;

      server_name server2;
}

autoindex on;
