/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   generateAutoindexHTML.cpp                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: vblanc <vblanc@student.42lyon.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/12/11 17:37:13 by vblanc            #+#    #+#             */
/*   Updated: 2025/12/11 18:58:16 by vblanc           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "utils.hpp"

static std::string generateListItem(std::string &name)
{
    return std::string("    <li><a href=\"" + name + "\">" + name + "</a></li>\n");
}

std::string generateAutoindexHTML(const std::string &path)
{
    DIR *dr = opendir(path.c_str());

    if (dr == NULL)
        throw std::runtime_error(RED "Could not open directory" DEFAULT);

    std::string page, name;

    page = "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"UTF-8\">\n  <title>Index of " + path + "</title>\n  ";
    page += "<style>\n    body {\n      font-family: Arial, sans-serif;\n      margin: 30px;\n      background: #f7f7f7;\n    }\n    ";
    page += ".container {\n      max-width: 700px;\n      margin: auto;\n      background: white;\n      padding: 25px;\n      border-radius: 8px;\n      box-shadow: 0 4px 10px rgba(0,0,0,0.08);\n    }\n    ";
    page += "h1 {\n      text-align: center;\n      font-size: 26px;\n      margin-bottom: 20px;\n      color: #333;\n    }\n    ";
    page += "ul {\n      list-style: none;\n      padding-left: 0;\n      font-size: 18px;\n      }\n    li {\n      padding: 6px 0;\n    }\n    ";
    page += "a {\n      text-decoration: none;\n      color: #0077cc;\n      font-weight: 500;\n    }\n    a:hover {\n      text-decoration: underline;\n    }\n    ";
    page += ".foot {\n      margin-top: 25px;\n      text-align: center;\n      font-size: 14px;\n      color: #777;\n    }\n    hr {\n      margin: 20px 0;\n    }\n    ";
    page += "</style>\n</head>\n<body>\n  <div class=\"container\">\n  <h1>Index of " + path + "</h1>\n  <hr>\n  <ul>\n";

    std::vector<std::string> names;

    struct dirent *de;
    while ((de = readdir(dr)) != NULL)
    {
        name = de->d_name;
        if (name != "." && name != "..")
        {
            if (de->d_type & DT_DIR)
                name.append("/");
            names.push_back(name);
        }
    }

    std::sort(names.begin(), names.end());

    for (std::size_t i = 0; i < names.size(); i++)
        page.append(generateListItem(names.at(i)));

    page += "  </ul>\n  </hr>\n    <div class=\"foot\">Autoindex generated by webserv</div>\n</body>\n</html>\n";

    closedir(dr);
    return page;
}
