#!/usr/bin/env python3
"""
cgi-bin/hello.py
Simplest CGI: outputs headers + HTML body.
WebServ must fork/exec this, capture stdout, and forward it to the client.
"""

import os
import datetime

# --- Parse QUERY_STRING manually (no cgi module dependency) ---
qs = os.environ.get("QUERY_STRING", "")
params = {}
if qs:
    for pair in qs.split("&"):
        if "=" in pair:
            k, v = pair.split("=", 1)
            params[k] = v.replace("+", " ").replace("%20", " ")

name   = params.get("name", "World")
lang   = params.get("lang", "en")
now    = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
method = os.environ.get("REQUEST_METHOD", "GET")
server = os.environ.get("SERVER_NAME", "localhost")
port   = os.environ.get("SERVER_PORT", "8080")

# --- CGI Response ---
# Headers MUST come first, followed by a blank line
print("Content-Type: text/html; charset=utf-8")
print("X-CGI-Script: hello.py")
print("X-Powered-By: WebServ/42")
print()  # ← blank line separates headers from body

print(f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
  <meta charset="UTF-8">
  <title>Hello CGI</title>
  <style>
    body {{ font-family: monospace; background: #0a0a0f; color: #e8e8f0; padding: 2rem; }}
    h1   {{ color: #00ff9d; }}
    table {{ border-collapse: collapse; margin-top: 1rem; }}
    td, th {{ padding: .4rem 1rem; border: 1px solid #2a2a3d; text-align: left; }}
    th {{ color: #7c6bff; }}
    .label {{ color: #888899; }}
  </style>
</head>
<body>
  <h1>Hello, {name}!</h1>
  <p>This response was generated by <strong>hello.py</strong> via CGI.</p>
  <table>
    <tr><th>Variable</th><th>Value</th></tr>
    <tr><td class="label">REQUEST_METHOD</td><td>{method}</td></tr>
    <tr><td class="label">QUERY_STRING</td><td>{qs or "(empty)"}</td></tr>
    <tr><td class="label">SERVER_NAME</td><td>{server}</td></tr>
    <tr><td class="label">SERVER_PORT</td><td>{port}</td></tr>
    <tr><td class="label">Timestamp</td><td>{now}</td></tr>
    <tr><td class="label">name param</td><td>{name}</td></tr>
  </table>
</body>
</html>""")
